sudo: false
language: node_js
node_js:
  - 8.5.0
env:
  global:
    - YARN_VERSION=1.0.1

before_install:
  - export PATH="$HOME/.yarn/bin:$PATH"
  - |
    if [[ ! -e ~/.yarn/bin/yarn || $(yarn --version) != "${YARN_VERSION}" ]]; then
      curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
    fi

script:
  - yarn run eslint
  - yarn run test
  - yarn run pkg
  - ./tasks/zip.sh

after_success:
  - ./node_modules/.bin/codecov
  - |
    if [ "$TRAVIS_BRANCH" == 'master' ] && [ "$TRAVIS_PULL_REQUEST" == 'false' ]; then
      ./tasks/deploy.sh
    fi

cache:
  yarn: true
  directories:
    - "~/.yarn"
    - node_modules

deploy:
  - provider: releases
    api_key:
      secure: W6RLAW4INlstaOcxfwvtdiGonVK/dCQs1YTJ15bAQF6+aVjZRTX+RHUwgQipDqZofSbmbEyAYQ7pCjBUer5vCklAbInYNtkCr4zLBPIMHMsvLJ6AALHkuXDRgspF3EO29v7U+gLoK0k3+MzIrZ/1opHmzURWD3LqNuaJHJa/7n7OndmACVOwYB/ijgDCIVF2F7ttBVeE3dR5f5zSAz4xcG91Cz17jvI+ZGAvAiB4ScOFxB+M/1yDleYXz599O9fMYSjLRV7ieu63/HxpH6kXTia+jRgWC7oTvVQZI1cDRmpTdjrxyuyuQH5NY+9bcjsM7T5jEfU1FUEu9hraU2Ig+VFXZVQ/3yyGHZ32MNaU6A5eRH5VX6wV3mYaU6m3h6FkvZZUJb6Fszxxd/b3BeYy2Rno5M+mX5cWZyCGCk6LdOfNoACn/M5UsCmn7IpGYFnWlEk+e/vtpb1OBHcf0MRQqClO9GtYst12GVke7b2u5WJRBWUmCnJH9Nrfu7CBmGwGuWELTncS/UXqzs7CwPmLHjHMmI3vRBi7Em/ohy00nO9gDbo254bJYhfMSDHXKUFXqsUnR1NF+UxbdLuQ1pIjmYQgnw4kIhjepiyvq8Ubyk8k2sJgoBjZNtV/Ob1VvJYcQnqZi7nmk3FwdfMj7Vb/Kvgh8uidHDmIw6/b1sljv/w=
    file_glob: true
    skip_cleanup: true
    file: "./pkg/*"
    on:
      repo: evenchange4/micro-github-latest
      tags: true
  - provider: npm
    email: evenchange4@gmail.com
    api_key:
      secure: kNk0MTZTTfjMCN0fiidV3CtbgrrjhADxysIgNUi6L93H+/YRZQvSqZDlt9ADH2HsPXRgYckS6f+uX94m/RJmJw2AGv9nh+ygkXU8Jkw+qnEdSf1vR5PIpXNn5cnZcQ6848bH8hTrOh4cZCMDEWBD59jHb54EGKphcc3McnRUnVQKRsviBSIwOZL8pCMw9+z4boY5jKxW0xHGPSpHjisUk4Ok7s0Lm2Lb84lF29wPkKFMdA53ZyikBkueSHnC2DssuFLZ3OatbSFl4peXUOWncVp+davtK88i6kNDp1mmRe5McS4bmHneCSemwWmu/erVZ0rSutphxNhZ32hpxOEKCneYWhApiG8+3R701nI1F6bfYyN7y7CtCeA9n6sk2zq1uKlVUnIRTLdpfAuz9xDuJq9VjYD7a3nGjgVazgsqUKgPqkd0CtZmgNLHJemjQz3Z0/zYwUYKtLE0cKajNZrQXAsr24Ldog6Pt4do+Xn6sgPZ0tAeve9orAJCZdJfzQtZ0jxoYASf2ksM/JPDInKC+I8YKQom2QV3aPQKJkBbRDE078A4uBZhsGuSdw/2KW71DbZcwh+CfVP8iWwQEla23Kw4zmvw0V43uUHDBL5pS/lHymnvItdGba8/G43uzIf1zMZ4sgscIQAIq3EjDcULCBSAlv15l9bqykTLRKotz8w=
    on:
      repo: evenchange4/micro-github-latest
      tags: true

notifications:
  email: evenchange4@gmail.com
